package: yform_calhelper
version: '0.0.1'
author: 'Thomas Skerbis'
supportpage: https://github.com/skerbis/yform_calhelper
requires:
    php:
        version: '>8.2,<9'
    redaxo: ^5.17
    packages:
        yform: '^4'
