package: yform_calendar
version: '1.0.1-dev'
author: 'Friends of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_calendar/
requires:
    php:
        version: '>8.2,<9'
    redaxo: ^5.17
    packages:
        yform: '^4'
